### ISSUE TITLE
Floating point exception(core dumped)

### ISSUE THREAD

**Issue by SIJAE-WOO** [dellytools/delly#217] opened 2020-12-16 01:25 UTC
Hi, I ran delly for cnv detection. But, I got the same errors in mutiple samples.
One of the errors is like below.

[2020-Dec-16 02:12:36] delly cnv -o /home/delly_cnv/delly_cnv_test1.bcf -g /data/Reference/1000Genomes/GRCh38_full_analysis_set_plus_decoy_hla.fa -m /data/Reference/Tool_reference/delly/Homo_sapiens.GRCh38.dna.primary_assembly.fa.r101.s501.blacklist.gz -l /home/delly/test1.bcf /home/test/test1_sorted.bam
[2020-Dec-16 02:13:18] Scanning Windows

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2020-Dec-16 04:50:26] Estimate GC bias

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[2020-Dec-16 07:27:59] Count fragments

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*/var/spool/torque/mom_priv/jobs/7437.localhost.SC: line 1: 64081 Floating point exception(core dumped) delly cnv -o /home/delly_cnv/delly_cnv_test1.bcf -g /data/Reference/1000Genomes/GRCh38_full_analysis_set_plus_decoy_hla.fa -m /data/Reference/Tool_reference/delly/Homo_sapiens.GRCh38.dna.primary_assembly.fa.r101.s501.blacklist.gz -l /home/delly/test1.bcf /home/test/test1_sorted.bam

I don't know why this error occurs and how to solve this problem.
If you know a solution, please let me know.

Bests,

Sijae

**Comment by tobiasrausch** [comment] 2020-12-16 07:40
Hi Sijae,

Thanks for reporting this likely bug. Is this low coverage data? Can you share one of these BAM files for debugging?

Thanks, Tobias

**Comment by SIJAE-WOO** [comment] 2020-12-16 08:56
Hi Tobias,Actually, I had this likely bug in at least 30-40 samples. And those are not low coverage data. I can share one BAM file, but the file size is 57G. How can I share the file? Also, the BAM file is unpublished data, so please don't use and distribute the file for other purposes except debugging.

**Comment by tobiasrausch** [comment] 2020-12-16 11:58
Thanks, can you please send me a regular email to rausch@embl.de ? Then I
can send you an upload link to our aspera server for the data. I will of
course delete the data afterwards.

**Comment by SIJAE-WOO** [comment] 2020-12-16 13:08
I sent an email.

**Comment by tobiasrausch** [comment] 2020-12-16 13:15
Thanks.

**Comment by SIJAE-WOO** [comment] 2020-12-17 23:12
Hi,I uploaded the BAM file.

**Comment by tobiasrausch** [comment] 2020-12-18 15:30
Did you use the release version available [here](https://github.com/dellytools/delly/releases)? On the BAM file you shared this version just worked fine. I don't see any issues.

**Comment by tobiasrausch** [comment] 2020-12-18 15:34
Or maybe it's related to the `-l` option? I will check this.

**Comment by SIJAE-WOO** [comment] 2020-12-18 15:47
I used just the release version. And I used the `-l` option. I didn't try without `-l` option. I thought the option could give an additive effect on performance. Whether the `-l` option is used or not used could make a considerable difference in performance?

**Comment by tobiasrausch** [comment] 2020-12-20 19:43
The bug was indeed caused by the `-l` option, it's fixed now in the github code. Can you please try if it works now? Without `-l` `delly cnv` only uses read-depth information and thus, the breakpoint accuracy is not that great. With `-l` `delly cnv` takes paired-end and split-read breakpoints into account, improving breakpoint accuracy and copy-number estimates.

**Comment by SIJAE-WOO** [comment] 2020-12-26 08:11
Hi Tobias,
Thank you for fixing the bug! I retried delly cnv with and without `-l` option. In the cases without `-l` option, delly works well. And delly(fixed version) works well, but I got another error in filtering for germline CNVs step. I tried my samples by the same commands except `-l` option.  I think this error maybe be also resulted from the same cause. Could you check the error, please?

**Comment by SIJAE-WOO** [comment] 2020-12-27 09:04
I tried delly cnv for same samples one more time with same options except only different window option. But I got same error in delly classify step! Please check the delly classify codes.

delly classify -f germline -o delly_cnv_filtered.bcf delly_cnv_merged.bcf
[2020-Dec-27 18:03:58] delly classify -f germline -o delly_cnv_filtered.bcf delly_cnv_merged.bcf
[2020-Dec-27 18:03:58] Filtering VCF/BCF file
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::math::rounding_error> >'
  what():  Error in function boost::math::round<float>(float): Value nan can not be represented in the target integer type.
Aborted (core dumped)

**Comment by tobiasrausch** [comment] 2020-12-27 19:51
This should also be fixed now. The classifier now first checks for infinity and NaN.

**Comment by SIJAE-WOO** [comment] 2020-12-28 01:25
The classifier works well! Thank you for your rapid response. I have one question about `-l` option details. The number of my samples is about 230. When CNVs in a targeted region were detected well after germline filtering in without `-l` option, but the number of CNV is 0 after germline filtering in with `-l`. I want to know whether the `-l` option is used for only specificity, not sensitivity.

**Comment by tobiasrausch** [comment] 2020-12-28 11:36
`-l` should improve the breakpoint accuracy of CNVs. This may improve the copy-number estimates slightly but I would not expect massive changes. `-l` is not about sensitivity or specificity.

**Comment by SIJAE-WOO** [comment] 2020-12-28 11:51
I'll recheck the results. Thank you.

**Comment by tobiasrausch** [comment] 2020-12-29 09:09
Thanks, if there are any further problems just open a new issue. I think this one is fixed.

**Closed by tobiasrausch** 2020-12-29 09:09 UTC
Labels: bug
