### ISSUE TITLE
delly producing 0-based bcf

### ISSUE THREAD

**Issue by amandaseuss** [dellytools/delly#136] opened 2018-09-10 21:09 UTC
Shouldn't the bcf files produced be one-based?
Downstream tool bedtools doesn't like it...
example:
`Error: Invalid record... Record is 
My_Primary_000007F_quiver	0	DUP00000736	N	<DUP>	.	PASS	PRECISE;SVTYPE=DUP;SVMETHOD=EMBL.DELLYv0.7.8;CHR2=My_Primary_000007F_quiver;END=170012;PE=17;MAPQ=49;CT=5to3;CIPOS=-27,27;CIEND=-27,27;INSLEN=0;HOMLEN=28;SR=10;SRQ=1;CONSENSUS=GAGCCCTTTCATCACTATCATTGCACCTTTTAGAATCTTCAGTGTTCTATTATCAATTTTTATTGTACAACCCATTGAGTCTATCATACCCAAAGAAATCAAGTTTCTTTTTAAGT;CE=1.86087	GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV	0/1:-75.0725,0,-6.94407:69:PASS:0:3930:0:-1:35:27:4:23	0/1:-31.0868,0,-11.7872:118:PASS:0:2975:0:-1:24:18:4:9	0/1:-50.4796,0,-10.0227:100:PASS:0:3121:0:-1:29:19:4:16	0/1:-80.9704,0,-15.1716:152:PASS:0:5049:0:-1:37:21:6:23	0/1:-75.3734,0,-8.03346:80:PASS:0:4067:0:-1:32:25:4:22	0/1:-59.0736,0,-24.0787:10000:PASS:0:4704:0:-1:30:11:8:18	0/1:-84.1693,0,-15.1706:152:PASS:0:4920:0:-1:36:22:6:24	0/1:-34.6877,0,-4.48842:45:PASS:0:3926:0:-1:24:20:2:10	0/1:-20.3918,0,-5.59221:56:PASS:0:2091:0:-1:15:10:2:6	0/1:-45.9818,0,-9.94746:99:PASS:0:4344:0:-1:31:31:4:14	0/1:-28.0859,0,-15.3897:154:PASS:0:4077:0:-1:29:32:5:9	0/1:-28.7887,0,-4.90092:49:PASS:0:4012:0:-1:40:21:2:9	0/1:-45.5806,0,-10.7055:107:PASS:0:4203:0:-1:33:16:4:15	0/1:-48.1797,0,-17.6803:10000:PASS:0:3484:0:-1:38:19:6:14	0/1:-50.6826,0,-6.68314:67:PASS:0:3767:0:-1:32:25:3:14	0/1:-63.4725,0,-20.2803:10000:PASS:0:2556:0:-1:0:0:7:20`

**Comment by tobiasrausch** [comment] 2018-09-26 19:50
According to the VCF spec "Telomeres are indicated by using positions 0 or N+1, where N is the length of the corresponding chromosome or contig.  (Integer, Required)". I probably won't fix this.

**Comment by amandaseuss** [comment] 2018-09-26 19:55
Ok. For a genome assembly at contig resolution, however, these aren't telomeres, just the ends of contigs which may or may not include telomere regions.

**Comment by tobiasrausch** [comment] 2018-09-26 19:58
Sure, is this just causing problems with Bedtools? If multiple downstream tools are affected I am really willing to reconsider this and maybe set these calls to 1.

**Comment by tobiasrausch** [comment] 2018-09-26 20:00
Just to clarify, the problem is very simple: Delly estimates the breakpoints based on the insert size and because of that SVs close to the telomere could have a negative coordinate which is then set to 0.

**Comment by amandaseuss** [comment] 2018-09-26 20:15
Yep, I suspected something like that was what was going on.  I've just been filtering out these few SV calls (there's only 3 with a zero coordinate). With my assembly, I don't know that I can make much biological sense of SVs that happen at contig ends anyway. At least for my experiment, the problem would probably resolve itself if my assembly was more contiguous. 

This only seems to cause an issue with bedtools. I'm using it to compare lumpy and delly outputs.

**Comment by tobiasrausch** [comment] 2019-02-04 10:12
Fixed in delly v0.8.1.

**Closed by tobiasrausch** 2019-02-04 10:12 UTC
Labels: enhancement
