### ISSUE TITLE
Keep getting "core dumped" error on Delly2 tool

### ISSUE THREAD

**Issue by W4RJ4** [dellytools/delly#140] opened 2018-11-14 09:55 UTC
terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::substr
Aborted (core dumped)

i'm working with GRCh38 bam file and appropriate fasta file.

**Comment by tobiasrausch** [comment] 2018-11-14 15:05
What aligner are you using? Looks like cutting a reference slice for SV alignment caused a segfault. Are you using an exclude map to remove the alternative haplotypes and unplaced contigs in GRCh38? If you can share a small slice of that BAM that reproduces the error I am happy to debug this further. Thanks.

**Comment by W4RJ4** [comment] 2018-11-15 14:47
Hi, Tobias, thanks for reply. I'm using bwa_mem and i'm not using exclude map file. Also, this error occurs in less than 1% of my samples. 

Sorry, I'm working with controlled access data.

Also, I have a step where i'm using SAMtools View to transfer CRAM to BAM, can this be the issue?

**Comment by tobiasrausch** [comment] 2018-11-15 15:15
I would suspect that this is happening on an unplaced contig so the exclude map might help. Delly accepts CRAM files so there is no need to convert to BAM. Without the BAM file it will be hard for me to track down this error. If you want to have a closer look you could also try picard validatesamfile just to see if the BAM file is indeed fine.

https://broadinstitute.github.io/picard/command-line-overview.html#ValidateSamFile

**Comment by tobiasrausch** [comment] 2019-02-04 10:12
I hope that's resolved by now. If not, could you please try delly v0.8.1? If that version still crashes please re-open this issue.

**Closed by tobiasrausch** 2019-02-04 10:12 UTC
Labels: bug
