### ISSUE TITLE
'Fail to open index' when .bai file is symlinked

### ISSUE THREAD

**Issue by stevekm** [dellytools/delly#93] opened 2018-01-29 20:14 UTC
When I try to run Delly2 with .bam and .bai files that are symlinked in a directory, I get an error that the .bai index file cannot be read:

```bash
$ ll
lrwxrwxrwx 1 kellys04 molecpathlab  139 Jan 29 15:01 2JF-A-Tumor-HGSOC.dd.ra.rc.bam -> /path/to/2JF-A-Tumor-HGSOC.dd.ra.rc.bam
lrwxrwxrwx 1 kellys04 molecpathlab  143 Jan 29 15:01 2JF-A-Tumor-HGSOC.dd.ra.rc.bam.bai -> /path/to/2JF-A-Tumor-HGSOC.dd.ra.rc.bam.bai


$ delly call -t INV -g /path/to/genome.fa -o inversions.bcf "2JF-A-Tumor-HGSOC.dd.ra.rc.bam"
Fail to open index for 2JF-A-Tumor-HGSOC.dd.ra.rc.bam
```

If I replace the symlink to the .bai file with a copy of the .bai, it works. However, this does not work well with my pipeline, which uses symlinks to files for staging. Is there a way to tell Delly2 to detect the symlinked .bai file?

**Comment by tobiasrausch** [comment] 2018-01-30 13:26
Hi,

I cannot reproduce this error with the latest delly version v0.7.8. Can you try delly v0.7.8 without the -t option? A static binary is available here https://github.com/dellytools/delly/releases or on bioconda. All the BAM file handling is done using HTSlib but I couldn't find an open issue for symlinks so I am a bit puzzled by this error. If v0.7.8 works I would assume this is fixed by now.

Thanks, Tobias

**Comment by tobiasrausch** [comment] 2018-01-30 13:30
Because I am using HTSlib you can also try:

samtools view "2JF-A-Tumor-HGSOC.dd.ra.rc.bam" chr1:20000000-20500000 | head

This requires the index so maybe it helps pinpointing the error.

**Comment by tobiasrausch** [comment] 2018-03-31 11:37
Has this been resolved by the above suggestion? I will close this issue now but please re-open if you still have problems with that.

**Closed by tobiasrausch** 2018-03-31 11:37 UTC

**Comment by stevekm** [comment] 2018-03-31 16:19
thanks I think there was something messed up with that particular file, have not run into this error since then.
