### ISSUE TITLE
Delly 0.8.3 doesn't finish

### ISSUE THREAD

**Issue by StevenIg** [dellytools/delly#197] opened 2020-05-25 16:00 UTC
Hello,

I used Delly : v0.7.9 on two bam files and its runs well.

I have upgraded Delly to the lastest version: 
Delly version: v0.8.3
 using Boost: v1.53.0
 using HTSlib: v1.10.2

But for this version with the same command line stay block since 4 day : 

[2020-May-21 14:03:16] SV annotation

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**

command line : 
/home/software/delly_${version}/src/delly call -x /home/software/delly_${version}/excludeTemplates/human.hg38.excl.tsv -o SVs_Constit_Tumor_delly.bcf -g /home/genomes/Human_hg38/O
neFasta/hg38.fa Tumor.sorted.bam Constit.sorted.bam

Do you have a solution ?

Regards

Steven

**Comment by holtgrewe** [comment] 2020-05-28 19:56
Hi, I have a similar problem after upgrading from 0.8.0 to 0.8.3 on ~10 out of 400 genomes (germline).

Using `perf record -p PID` and `perf report`, I see that Delly is spending time the "stuck" time in a DP alignment function.

```
Overhead  Command  Shared Object                       Symbol
  34.46%  delly    delly                               [.] torali::needle<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::bas
  14.21%  delly    delly                               [.] std::vector<int, std::allocator<int> >::operator[]
   5.43%  delly    delly                               [.] std::max<int>
   5.21%  delly    delly                               [.] torali::_horizontalGap<false, unsigned long, unsigned long, int>
   5.02%  delly    delly                               [.] torali::_score<boost::multi_array<double, 2ul, std::allocator<double> >, unsigned long, torali::DnaScore<int> >
   3.38%  delly    delly                               [.] boost::dynamic_bitset<unsigned long, std::allocator<unsigned long> >::operator[]
   2.87%  delly    delly                               [.] torali::_verticalGap<true, unsigned long, unsigned long, int>
   2.54%  delly    delly                               [.] boost::dynamic_bitset<unsigned long, std::allocator<unsigned long> >::reference::reference
   2.25%  delly    delly                               [.] boost::dynamic_bitset<unsigned long, std::allocator<unsigned long> >::reference::do_assign
   1.84%  delly    delly                               [.] boost::dynamic_bitset<unsigned long, std::allocator<unsigned long> >::reference::do_set
   1.51%  delly    delly                               [.] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[]@plt
```

**Comment by tobiasrausch** [comment] 2020-06-04 08:01
Hi,

Sorry for my late reply. I was hoping that I run into this issue in one of the ~3,000 deep-coverage human genomes we just processed with delly but everything worked fine on this cohort. Given that delly is stuck in the SV annotation step at the DP alignment I suspect this is due to some huge pileup of reads or an excessive number of candidate SVs. Any chance that one of these problematic BAM files can be shared with me? If not, I will try to instrument the code to get a bit more insight where the problem is.

Thanks, Tobias

**Comment by tobiasrausch** [comment] 2020-08-08 12:14
Hi, 

I believe I could meanwhile reproduce this error in the DP alignment. This should be fixed now. There is also a new parameter -z which determines the min. clique size during SV discovery. This was in all previous delly versions set to 2 but with the advent of very deep WGS data >>30x it may make sense to set this to 5 or even higher to reduce the number of candidate SVs that are then genotyped. 

Anyway, I hope it's solved. If you still see runtime issues please reopen.

Thanks, Tobias

**Closed by tobiasrausch** 2020-08-08 12:14 UTC
Labels: bug

**Comment by holtgrewe** [comment] 2020-09-25 12:15
Thanks, could we get a release including this patch?

**Comment by tobiasrausch** [comment] 2020-09-29 08:44
Just released v0.8.5 which includes this patch.

**Comment by holtgrewe** [comment] 2020-09-29 08:53
@tobiasrausch thanks, do you update the bioconda recipe? I can do this...

**Comment by holtgrewe** [comment] 2020-09-29 08:56
Ah, the bot does it...
